--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lyubo/Wallpapers/bmw4k.jpg"

-- Special
background="#090807"
foreground="#e9dec9"
cursor="#e9dec9"

-- Colors
color0="#090807"
color1="#635E5B"
color2="#6E6D6D"
color3="#9C6253"
color4="#BB9964"
color5="#7A7F86"
color6="#999A99"
color7="#e9dec9"
color8="#a39b8c"
color9="#635E5B"
color10="#6E6D6D"
color11="#9C6253"
color12="#BB9964"
color13="#7A7F86"
color14="#999A99"
color15="#e9dec9"
