# Shell variables
# Generated by 'wal'
wallpaper='/home/lyubo/Wallpapers/LA_Streets.jpg'

# Special
background='#1a1a1b'
foreground='#c5c5c6'
cursor='#c5c5c6'

# Colors
color0='#1a1a1b'
color1='#764845'
color2='#827c71'
color3='#cb886c'
color4='#8ebd9e'
color5='#9bd0af'
color6='#e3b889'
color7='#c5c5c6'
color8='#535354'
color9='#764845'
color10='#827c71'
color11='#cb886c'
color12='#8ebd9e'
color13='#9bd0af'
color14='#e3b889'
color15='#c5c5c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
