--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lyubo/Wallpapers/LA_Streets.jpg"

-- Special
background="#1a1a1b"
foreground="#c5c5c6"
cursor="#c5c5c6"

-- Colors
color0="#1a1a1b"
color1="#764845"
color2="#827c71"
color3="#cb886c"
color4="#8ebd9e"
color5="#9bd0af"
color6="#e3b889"
color7="#c5c5c6"
color8="#535354"
color9="#764845"
color10="#827c71"
color11="#cb886c"
color12="#8ebd9e"
color13="#9bd0af"
color14="#e3b889"
color15="#c5c5c6"
